# Dockerfile
FROM debian:10

LABEL maintainer Jean-Noel VEGA <lajnv@hotmail.com>

EXPOSE 80

# install apache2

RUN apt-get update -yq && \
    apt-get install apache2 -yq

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN a2enmod rewrite deflate headers ssl

CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["apachectl"]

# install php

RUN apt-get update -yq && apt-get install php -yq
RUN apt-get install -yq \
    php-pdo \
    php-mysql \
    php-zip \
    php-gd \
    php-mbstring \
    php-curl \
    php-xml \
    php-pear \
    php-bcmath

# install wordpress

RUN rm /var/www/html/index.html
WORKDIR /tmp
RUN apt-get update -yq && apt-get install -yq unzip wget
RUN wget https://wordpress.org/latest.zip
RUN unzip -q latest.zip -d /var/www/html
WORKDIR /var/www/html
RUN mv wordpress/* /var/www/html/ && \
    rm wordpress/ -Rf && \
    chown -R www-data:www-data /var/www/html
RUN find /var/www/html/ -type f -exec chmod 644 {} \;
RUN find /var/www/html/ -type d -exec chmod 755 {} \;
